### ISSUE TITLE
Not all mutations recognized (mutfile)

### ISSUE THREAD

**Issue by j0kaso** [KULL-Centre/PRISM#9]
Hey,

I have an input file with all mutations related to 1 residue where I have a new line for each mutation, e.g.:

```
V 104 A
V 104 C
...
V 104 T
V 104 V
V 104 W
V 104 Y
```

The current (also before the new alignment options) dev branch pipeline only recognizes `V 104 VY`. Although this might not be the right format(?) it would be nice to allow also this option. Also, I was wondering, why it pics _V&Y_ of all available options. 

Besides, it would be great to have a good description of the mutfile in the readme or documentation (or wiki here ;-))

Thanks!

**Comment by andershbf** [comment]
Hi j0kaso

Each line in the mutation input file should represent one residue position:
`V 104 ACTVWY`
The reason it picks V&Y is because if you have multiple inputs for one position it will overwrite and pick the latest, in this case Y. The WT is automatically added to each position and therefore the V is added too. 

It could be a cool idea to make the pipeline combine inputs for the same position (and of course remove duplicates) 

I will in the not too distant fitire, begin working on a more elaborate README and eventually a wiki page and hopefully these issues will become more clear.

Hope this solves your issue

Best,
Anders

**Comment by j0kaso** [comment]
Thanks for the clarification & sounds great you're looking into a more detailed README!

Maybe this issue (of allowing such a "bad" user input) could be tackled at the same time when I look at Issue #2
